<?php

/**
 * BasePacjent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $imie
 * @property string $nazwisko
 * @property string $pesel
 * @property date $data_urodzenia
 * @property enum $plec
 * @property smallint $wzrost
 * @property decimal $waga
 * @property enum $reka
 * @property Doctrine_Collection $Badania
 * @property Doctrine_Collection $Radioterapia
 * @property Doctrine_Collection $Chemioterapie
 * 
 * @method string              getImie()           Returns the current record's "imie" value
 * @method string              getNazwisko()       Returns the current record's "nazwisko" value
 * @method string              getPesel()          Returns the current record's "pesel" value
 * @method date                getDataUrodzenia()  Returns the current record's "data_urodzenia" value
 * @method enum                getPlec()           Returns the current record's "plec" value
 * @method smallint            getWzrost()         Returns the current record's "wzrost" value
 * @method decimal             getWaga()           Returns the current record's "waga" value
 * @method enum                getReka()           Returns the current record's "reka" value
 * @method Doctrine_Collection getBadania()        Returns the current record's "Badania" collection
 * @method Doctrine_Collection getRadioterapia()   Returns the current record's "Radioterapia" collection
 * @method Doctrine_Collection getChemioterapie()  Returns the current record's "Chemioterapie" collection
 * @method Pacjent             setImie()           Sets the current record's "imie" value
 * @method Pacjent             setNazwisko()       Sets the current record's "nazwisko" value
 * @method Pacjent             setPesel()          Sets the current record's "pesel" value
 * @method Pacjent             setDataUrodzenia()  Sets the current record's "data_urodzenia" value
 * @method Pacjent             setPlec()           Sets the current record's "plec" value
 * @method Pacjent             setWzrost()         Sets the current record's "wzrost" value
 * @method Pacjent             setWaga()           Sets the current record's "waga" value
 * @method Pacjent             setReka()           Sets the current record's "reka" value
 * @method Pacjent             setBadania()        Sets the current record's "Badania" collection
 * @method Pacjent             setRadioterapia()   Sets the current record's "Radioterapia" collection
 * @method Pacjent             setChemioterapie()  Sets the current record's "Chemioterapie" collection
 * 
 * @package    onko_gliwice
 * @subpackage model
 * @author     Paweł Dawczak pawel.dawczak@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePacjent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pacjent');
        $this->hasColumn('imie', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('nazwisko', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('pesel', 'string', 11, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 11,
             ));
        $this->hasColumn('data_urodzenia', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('plec', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'm',
              1 => 'k',
             ),
             ));
        $this->hasColumn('wzrost', 'smallint', null, array(
             'type' => 'smallint',
             'notnull' => true,
             ));
        $this->hasColumn('waga', 'decimal', 5, array(
             'type' => 'decimal',
             'scale' => 2,
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('reka', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'p',
              1 => 'l',
              2 => 'o',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Badanie as Badania', array(
             'local' => 'id',
             'foreign' => 'pacjent_id'));

        $this->hasMany('Radioterapia', array(
             'local' => 'id',
             'foreign' => 'pacjent_id'));

        $this->hasMany('Chemioterapia as Chemioterapie', array(
             'local' => 'id',
             'foreign' => 'pacjent_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}