<?php

/**
 * BaseUzywka
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $badanie_id
 * @property enum $typ
 * @property Badanie $Badanie
 * @property Doctrine_Collection $Cechy
 * 
 * @method integer             getBadanieId()  Returns the current record's "badanie_id" value
 * @method enum                getTyp()        Returns the current record's "typ" value
 * @method Badanie             getBadanie()    Returns the current record's "Badanie" value
 * @method Doctrine_Collection getCechy()      Returns the current record's "Cechy" collection
 * @method Uzywka              setBadanieId()  Sets the current record's "badanie_id" value
 * @method Uzywka              setTyp()        Sets the current record's "typ" value
 * @method Uzywka              setBadanie()    Sets the current record's "Badanie" value
 * @method Uzywka              setCechy()      Sets the current record's "Cechy" collection
 * 
 * @package    onko_gliwice
 * @subpackage model
 * @author     Paweł Dawczak pawel.dawczak@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUzywka extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('uzywka');
        $this->hasColumn('badanie_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('typ', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'ap',
              1 => 'bp',
              2 => 'np',
              3 => 'aa',
              4 => 'iu',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Badanie', array(
             'local' => 'badanie_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Cecha as Cechy', array(
             'local' => 'id',
             'foreign' => 'uzywka_id'));
    }
}