<?php

/**
 * BaseCecha
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $uzywka_id
 * @property integer $typ_cechy_id
 * @property string $wartosc
 * @property Uzywka $Uzywka
 * @property TypCechy $TypCechy
 * 
 * @method integer  getUzywkaId()     Returns the current record's "uzywka_id" value
 * @method integer  getTypCechyId()   Returns the current record's "typ_cechy_id" value
 * @method string   getWartosc()      Returns the current record's "wartosc" value
 * @method Uzywka   getUzywka()       Returns the current record's "Uzywka" value
 * @method TypCechy getTypCechy()     Returns the current record's "TypCechy" value
 * @method Cecha    setUzywkaId()     Sets the current record's "uzywka_id" value
 * @method Cecha    setTypCechyId()   Sets the current record's "typ_cechy_id" value
 * @method Cecha    setWartosc()      Sets the current record's "wartosc" value
 * @method Cecha    setUzywka()       Sets the current record's "Uzywka" value
 * @method Cecha    setTypCechy()     Sets the current record's "TypCechy" value
 * 
 * @package    onko_gliwice
 * @subpackage model
 * @author     Paweł Dawczak pawel.dawczak@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCecha extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cecha');
        $this->hasColumn('uzywka_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('typ_cechy_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('wartosc', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Uzywka', array(
             'local' => 'uzywka_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('TypCechy', array(
             'local' => 'typ_cechy_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}