<?php

/**
 * BaseProdukt
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nazwa
 * @property Doctrine_Collection $DietaProdukt
 * 
 * @method string              getNazwa()        Returns the current record's "nazwa" value
 * @method Doctrine_Collection getDietaProdukt() Returns the current record's "DietaProdukt" collection
 * @method Produkt             setNazwa()        Sets the current record's "nazwa" value
 * @method Produkt             setDietaProdukt() Sets the current record's "DietaProdukt" collection
 * 
 * @package    onko_gliwice
 * @subpackage model
 * @author     Paweł Dawczak pawel.dawczak@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProdukt extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('produkt');
        $this->hasColumn('nazwa', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('DietaProdukt', array(
             'local' => 'id',
             'foreign' => 'produkt_id'));
    }
}