<?php

/**
 * BaseWidmo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property blob $sdat
 * @property clob $spar
 * @property int $lokalizacja_id
 * @property decimal $rozmiar_voxela_x
 * @property decimal $rozmiar_voxela_y
 * @property decimal $rozmiar_voxela_z
 * @property integer $te
 * @property integer $tr
 * @property integer $ns
 * @property integer $wynik_id
 * @property WynikBadania $WynikBadania
 * @property Lokalizacja $Lokalizacja
 * 
 * @method blob         getSdat()             Returns the current record's "sdat" value
 * @method clob         getSpar()             Returns the current record's "spar" value
 * @method int          getLokalizacjaId()    Returns the current record's "lokalizacja_id" value
 * @method decimal      getRozmiarVoxelaX()   Returns the current record's "rozmiar_voxela_x" value
 * @method decimal      getRozmiarVoxelaY()   Returns the current record's "rozmiar_voxela_y" value
 * @method decimal      getRozmiarVoxelaZ()   Returns the current record's "rozmiar_voxela_z" value
 * @method integer      getTe()               Returns the current record's "te" value
 * @method integer      getTr()               Returns the current record's "tr" value
 * @method integer      getNs()               Returns the current record's "ns" value
 * @method integer      getWynikId()          Returns the current record's "wynik_id" value
 * @method WynikBadania getWynikBadania()     Returns the current record's "WynikBadania" value
 * @method Lokalizacja  getLokalizacja()      Returns the current record's "Lokalizacja" value
 * @method Widmo        setSdat()             Sets the current record's "sdat" value
 * @method Widmo        setSpar()             Sets the current record's "spar" value
 * @method Widmo        setLokalizacjaId()    Sets the current record's "lokalizacja_id" value
 * @method Widmo        setRozmiarVoxelaX()   Sets the current record's "rozmiar_voxela_x" value
 * @method Widmo        setRozmiarVoxelaY()   Sets the current record's "rozmiar_voxela_y" value
 * @method Widmo        setRozmiarVoxelaZ()   Sets the current record's "rozmiar_voxela_z" value
 * @method Widmo        setTe()               Sets the current record's "te" value
 * @method Widmo        setTr()               Sets the current record's "tr" value
 * @method Widmo        setNs()               Sets the current record's "ns" value
 * @method Widmo        setWynikId()          Sets the current record's "wynik_id" value
 * @method Widmo        setWynikBadania()     Sets the current record's "WynikBadania" value
 * @method Widmo        setLokalizacja()      Sets the current record's "Lokalizacja" value
 * 
 * @package    onko_gliwice
 * @subpackage model
 * @author     Paweł Dawczak pawel.dawczak@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWidmo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('widmo');
        $this->hasColumn('sdat', 'blob', null, array(
             'type' => 'blob',
             ));
        $this->hasColumn('spar', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('lokalizacja_id', 'int', 8, array(
             'type' => 'int',
             'length' => 8,
             ));
        $this->hasColumn('rozmiar_voxela_x', 'decimal', 5, array(
             'type' => 'decimal',
             'scale' => 2,
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('rozmiar_voxela_y', 'decimal', 5, array(
             'type' => 'decimal',
             'scale' => 2,
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('rozmiar_voxela_z', 'decimal', 5, array(
             'type' => 'decimal',
             'scale' => 2,
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('te', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('tr', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ns', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('wynik_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('WynikBadania', array(
             'local' => 'wynik_id',
             'foreign' => 'id'));

        $this->hasOne('Lokalizacja', array(
             'local' => 'lokalizacja_id',
             'foreign' => 'id'));
    }
}