<?php

/**
 * BaseBadanie
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $pacjent_id
 * @property date $data_badania
 * @property string $inne
 * @property boolean $menstruacja
 * @property Pacjent $Pacjent
 * @property Doctrine_Collection $Uzywki
 * @property WynikBadania $WynikBadania
 * @property Dieta $Dieta
 * 
 * @method integer             getPacjentId()    Returns the current record's "pacjent_id" value
 * @method date                getDataBadania()  Returns the current record's "data_badania" value
 * @method string              getInne()         Returns the current record's "inne" value
 * @method boolean             getMenstruacja()  Returns the current record's "menstruacja" value
 * @method Pacjent             getPacjent()      Returns the current record's "Pacjent" value
 * @method Doctrine_Collection getUzywki()       Returns the current record's "Uzywki" collection
 * @method WynikBadania        getWynikBadania() Returns the current record's "WynikBadania" value
 * @method Dieta               getDieta()        Returns the current record's "Dieta" value
 * @method Badanie             setPacjentId()    Sets the current record's "pacjent_id" value
 * @method Badanie             setDataBadania()  Sets the current record's "data_badania" value
 * @method Badanie             setInne()         Sets the current record's "inne" value
 * @method Badanie             setMenstruacja()  Sets the current record's "menstruacja" value
 * @method Badanie             setPacjent()      Sets the current record's "Pacjent" value
 * @method Badanie             setUzywki()       Sets the current record's "Uzywki" collection
 * @method Badanie             setWynikBadania() Sets the current record's "WynikBadania" value
 * @method Badanie             setDieta()        Sets the current record's "Dieta" value
 * 
 * @package    onko_gliwice
 * @subpackage model
 * @author     Paweł Dawczak pawel.dawczak@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBadanie extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('badanie');
        $this->hasColumn('pacjent_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('data_badania', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('inne', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('menstruacja', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Pacjent', array(
             'local' => 'pacjent_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Uzywka as Uzywki', array(
             'local' => 'id',
             'foreign' => 'badanie_id'));

        $this->hasOne('WynikBadania', array(
             'local' => 'id',
             'foreign' => 'badanie_id'));

        $this->hasOne('Dieta', array(
             'local' => 'id',
             'foreign' => 'badanie_id'));
    }
}