<?php

/**
 * BaseRadioterapia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property date $data_rozpoczecia
 * @property decimal $dawka_fr
 * @property decimal $dawka_total
 * @property date $data_zakonczenia
 * @property boolean $stereo
 * @property int $gtv
 * @property int $ctv
 * @property int $ptv
 * @property int $pacjent_id
 * @property Pacjent $Pacjent
 * 
 * @method date         getDataRozpoczecia()  Returns the current record's "data_rozpoczecia" value
 * @method decimal      getDawkaFr()          Returns the current record's "dawka_fr" value
 * @method decimal      getDawkaTotal()       Returns the current record's "dawka_total" value
 * @method date         getDataZakonczenia()  Returns the current record's "data_zakonczenia" value
 * @method boolean      getStereo()           Returns the current record's "stereo" value
 * @method int          getGtv()              Returns the current record's "gtv" value
 * @method int          getCtv()              Returns the current record's "ctv" value
 * @method int          getPtv()              Returns the current record's "ptv" value
 * @method int          getPacjentId()        Returns the current record's "pacjent_id" value
 * @method Pacjent      getPacjent()          Returns the current record's "Pacjent" value
 * @method Radioterapia setDataRozpoczecia()  Sets the current record's "data_rozpoczecia" value
 * @method Radioterapia setDawkaFr()          Sets the current record's "dawka_fr" value
 * @method Radioterapia setDawkaTotal()       Sets the current record's "dawka_total" value
 * @method Radioterapia setDataZakonczenia()  Sets the current record's "data_zakonczenia" value
 * @method Radioterapia setStereo()           Sets the current record's "stereo" value
 * @method Radioterapia setGtv()              Sets the current record's "gtv" value
 * @method Radioterapia setCtv()              Sets the current record's "ctv" value
 * @method Radioterapia setPtv()              Sets the current record's "ptv" value
 * @method Radioterapia setPacjentId()        Sets the current record's "pacjent_id" value
 * @method Radioterapia setPacjent()          Sets the current record's "Pacjent" value
 * 
 * @package    onko_gliwice
 * @subpackage model
 * @author     Paweł Dawczak pawel.dawczak@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRadioterapia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('radioterapia');
        $this->hasColumn('data_rozpoczecia', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('dawka_fr', 'decimal', 5, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 5,
             ));
        $this->hasColumn('dawka_total', 'decimal', 5, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 5,
             ));
        $this->hasColumn('data_zakonczenia', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('stereo', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('gtv', 'int', null, array(
             'type' => 'int',
             ));
        $this->hasColumn('ctv', 'int', null, array(
             'type' => 'int',
             ));
        $this->hasColumn('ptv', 'int', null, array(
             'type' => 'int',
             ));
        $this->hasColumn('pacjent_id', 'int', 8, array(
             'type' => 'int',
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Pacjent', array(
             'local' => 'pacjent_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}