<?php

/**
 * BaseLek
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nazwa_leku
 * @property enum $rodzaj
 * @property Doctrine_Collection $Chemioterapia
 * 
 * @method string              getNazwaLeku()     Returns the current record's "nazwa_leku" value
 * @method enum                getRodzaj()        Returns the current record's "rodzaj" value
 * @method Doctrine_Collection getChemioterapia() Returns the current record's "Chemioterapia" collection
 * @method Lek                 setNazwaLeku()     Sets the current record's "nazwa_leku" value
 * @method Lek                 setRodzaj()        Sets the current record's "rodzaj" value
 * @method Lek                 setChemioterapia() Sets the current record's "Chemioterapia" collection
 * 
 * @package    onko_gliwice
 * @subpackage model
 * @author     Paweł Dawczak pawel.dawczak@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLek extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('lek');
        $this->hasColumn('nazwa_leku', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('rodzaj', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'a',
              1 => 'c',
              2 => 'i',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Chemioterapia', array(
             'local' => 'id',
             'foreign' => 'lek_id'));
    }
}