<?php

/**
 * BaseWynikBadania
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property enum $ocena_stanu_guza
 * @property integer $badanie_id
 * @property blob $sdat
 * @property clob $spar
 * @property Badanie $Badanie
 * @property Doctrine_Collection $Widma
 * 
 * @method enum                getOcenaStanuGuza()   Returns the current record's "ocena_stanu_guza" value
 * @method integer             getBadanieId()        Returns the current record's "badanie_id" value
 * @method blob                getSdat()             Returns the current record's "sdat" value
 * @method clob                getSpar()             Returns the current record's "spar" value
 * @method Badanie             getBadanie()          Returns the current record's "Badanie" value
 * @method Doctrine_Collection getWidma()            Returns the current record's "Widma" collection
 * @method WynikBadania        setOcenaStanuGuza()   Sets the current record's "ocena_stanu_guza" value
 * @method WynikBadania        setBadanieId()        Sets the current record's "badanie_id" value
 * @method WynikBadania        setSdat()             Sets the current record's "sdat" value
 * @method WynikBadania        setSpar()             Sets the current record's "spar" value
 * @method WynikBadania        setBadanie()          Sets the current record's "Badanie" value
 * @method WynikBadania        setWidma()            Sets the current record's "Widma" collection
 * 
 * @package    onko_gliwice
 * @subpackage model
 * @author     Paweł Dawczak pawel.dawczak@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWynikBadania extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('wynik_badania');
        $this->hasColumn('ocena_stanu_guza', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'wz',
              1 => 'pr',
              2 => 'stg',
              3 => 'bcg',
             ),
             ));
        $this->hasColumn('badanie_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('sdat', 'blob', null, array(
             'type' => 'blob',
             ));
        $this->hasColumn('spar', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Badanie', array(
             'local' => 'badanie_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Widmo as Widma', array(
             'local' => 'id',
             'foreign' => 'wynik_id'));
    }
}