<?php

/**
 * BaseChemioterapia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property date $data_rozpoczecia
 * @property date $data_zakonczenia
 * @property integer $lek_id
 * @property integer $pacjent_id
 * @property Lek $Lek
 * @property Pacjent $Pacjent
 * 
 * @method date          getDataRozpoczecia()  Returns the current record's "data_rozpoczecia" value
 * @method date          getDataZakonczenia()  Returns the current record's "data_zakonczenia" value
 * @method integer       getLekId()            Returns the current record's "lek_id" value
 * @method integer       getPacjentId()        Returns the current record's "pacjent_id" value
 * @method Lek           getLek()              Returns the current record's "Lek" value
 * @method Pacjent       getPacjent()          Returns the current record's "Pacjent" value
 * @method Chemioterapia setDataRozpoczecia()  Sets the current record's "data_rozpoczecia" value
 * @method Chemioterapia setDataZakonczenia()  Sets the current record's "data_zakonczenia" value
 * @method Chemioterapia setLekId()            Sets the current record's "lek_id" value
 * @method Chemioterapia setPacjentId()        Sets the current record's "pacjent_id" value
 * @method Chemioterapia setLek()              Sets the current record's "Lek" value
 * @method Chemioterapia setPacjent()          Sets the current record's "Pacjent" value
 * 
 * @package    onko_gliwice
 * @subpackage model
 * @author     Paweł Dawczak pawel.dawczak@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseChemioterapia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('chemioterapia');
        $this->hasColumn('data_rozpoczecia', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('data_zakonczenia', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('lek_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('pacjent_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Lek', array(
             'local' => 'lek_id',
             'foreign' => 'id'));

        $this->hasOne('Pacjent', array(
             'local' => 'pacjent_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}