<?php

/**
 * BaseWidmo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property clob $skala_ppm
 * @property clob $widmo
 * @property clob $linia_bazowa
 * @property clob $widmo_bazowa
 * @property enum $lokalizacja
 * @property decimal $rozmiar_voxela_x
 * @property decimal $rozmiar_voxela_y
 * @property decimal $rozmiar_voxela_z
 * @property clob $stezenia
 * @property integer $te
 * @property integer $tr
 * @property integer $ns
 * @property integer $wynik_id
 * @property WynikBadania $WynikBadania
 * 
 * @method clob         getSkalaPpm()         Returns the current record's "skala_ppm" value
 * @method clob         getWidmo()            Returns the current record's "widmo" value
 * @method clob         getLiniaBazowa()      Returns the current record's "linia_bazowa" value
 * @method clob         getWidmoBazowa()      Returns the current record's "widmo_bazowa" value
 * @method enum         getLokalizacja()      Returns the current record's "lokalizacja" value
 * @method decimal      getRozmiarVoxelaX()   Returns the current record's "rozmiar_voxela_x" value
 * @method decimal      getRozmiarVoxelaY()   Returns the current record's "rozmiar_voxela_y" value
 * @method decimal      getRozmiarVoxelaZ()   Returns the current record's "rozmiar_voxela_z" value
 * @method clob         getStezenia()         Returns the current record's "stezenia" value
 * @method integer      getTe()               Returns the current record's "te" value
 * @method integer      getTr()               Returns the current record's "tr" value
 * @method integer      getNs()               Returns the current record's "ns" value
 * @method integer      getWynikId()          Returns the current record's "wynik_id" value
 * @method WynikBadania getWynikBadania()     Returns the current record's "WynikBadania" value
 * @method Widmo        setSkalaPpm()         Sets the current record's "skala_ppm" value
 * @method Widmo        setWidmo()            Sets the current record's "widmo" value
 * @method Widmo        setLiniaBazowa()      Sets the current record's "linia_bazowa" value
 * @method Widmo        setWidmoBazowa()      Sets the current record's "widmo_bazowa" value
 * @method Widmo        setLokalizacja()      Sets the current record's "lokalizacja" value
 * @method Widmo        setRozmiarVoxelaX()   Sets the current record's "rozmiar_voxela_x" value
 * @method Widmo        setRozmiarVoxelaY()   Sets the current record's "rozmiar_voxela_y" value
 * @method Widmo        setRozmiarVoxelaZ()   Sets the current record's "rozmiar_voxela_z" value
 * @method Widmo        setStezenia()         Sets the current record's "stezenia" value
 * @method Widmo        setTe()               Sets the current record's "te" value
 * @method Widmo        setTr()               Sets the current record's "tr" value
 * @method Widmo        setNs()               Sets the current record's "ns" value
 * @method Widmo        setWynikId()          Sets the current record's "wynik_id" value
 * @method Widmo        setWynikBadania()     Sets the current record's "WynikBadania" value
 * 
 * @package    onko_gliwice
 * @subpackage model
 * @author     Paweł Dawczak pawel.dawczak@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWidmo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('widmo');
        $this->hasColumn('skala_ppm', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('widmo', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('linia_bazowa', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('widmo_bazowa', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('lokalizacja', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'wz',
              1 => 'isc',
              2 => 'isp',
             ),
             ));
        $this->hasColumn('rozmiar_voxela_x', 'decimal', 5, array(
             'type' => 'decimal',
             'scale' => 2,
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('rozmiar_voxela_y', 'decimal', 5, array(
             'type' => 'decimal',
             'scale' => 2,
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('rozmiar_voxela_z', 'decimal', 5, array(
             'type' => 'decimal',
             'scale' => 2,
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('stezenia', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('te', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('tr', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ns', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('wynik_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('WynikBadania', array(
             'local' => 'wynik_id',
             'foreign' => 'id'));
    }
}