<?php

/**
 * BaseDietaProdukt
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $dieta_id
 * @property integer $produkt_id
 * @property boolean $duza_ilosc
 * @property Dieta $Dieta
 * @property Produkt $Produkt
 * 
 * @method integer      getDietaId()    Returns the current record's "dieta_id" value
 * @method integer      getProduktId()  Returns the current record's "produkt_id" value
 * @method boolean      getDuzaIlosc()  Returns the current record's "duza_ilosc" value
 * @method Dieta        getDieta()      Returns the current record's "Dieta" value
 * @method Produkt      getProdukt()    Returns the current record's "Produkt" value
 * @method DietaProdukt setDietaId()    Sets the current record's "dieta_id" value
 * @method DietaProdukt setProduktId()  Sets the current record's "produkt_id" value
 * @method DietaProdukt setDuzaIlosc()  Sets the current record's "duza_ilosc" value
 * @method DietaProdukt setDieta()      Sets the current record's "Dieta" value
 * @method DietaProdukt setProdukt()    Sets the current record's "Produkt" value
 * 
 * @package    onko_gliwice
 * @subpackage model
 * @author     Paweł Dawczak pawel.dawczak@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDietaProdukt extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dieta_produkt');
        $this->hasColumn('dieta_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('produkt_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('duza_ilosc', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Dieta', array(
             'local' => 'dieta_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Produkt', array(
             'local' => 'produkt_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}