<?php

/**
 * BaseRodzajRadioterapii
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $skrot
 * @property string $nazwa
 * @property Doctrine_Collection $Radioterapia
 * 
 * @method string              getSkrot()        Returns the current record's "skrot" value
 * @method string              getNazwa()        Returns the current record's "nazwa" value
 * @method Doctrine_Collection getRadioterapia() Returns the current record's "Radioterapia" collection
 * @method RodzajRadioterapii  setSkrot()        Sets the current record's "skrot" value
 * @method RodzajRadioterapii  setNazwa()        Sets the current record's "nazwa" value
 * @method RodzajRadioterapii  setRadioterapia() Sets the current record's "Radioterapia" collection
 * 
 * @package    onko_gliwice
 * @subpackage model
 * @author     Paweł Dawczak pawel.dawczak@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRodzajRadioterapii extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rodzaj_radioterapii');
        $this->hasColumn('skrot', 'string', 5, array(
             'type' => 'string',
             'length' => 5,
             ));
        $this->hasColumn('nazwa', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Radioterapia', array(
             'local' => 'id',
             'foreign' => 'rodzaj_radioterapii_id'));
    }
}