<?php

/**
 * BaseTypCechy
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nazwa
 * @property enum $typ
 * @property Doctrine_Collection $Cecha
 * 
 * @method string              getNazwa() Returns the current record's "nazwa" value
 * @method enum                getTyp()   Returns the current record's "typ" value
 * @method Doctrine_Collection getCecha() Returns the current record's "Cecha" collection
 * @method TypCechy            setNazwa() Sets the current record's "nazwa" value
 * @method TypCechy            setTyp()   Sets the current record's "typ" value
 * @method TypCechy            setCecha() Sets the current record's "Cecha" collection
 * 
 * @package    onko_gliwice
 * @subpackage model
 * @author     Paweł Dawczak pawel.dawczak@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTypCechy extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('typ_cechy');
        $this->hasColumn('nazwa', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 30,
             ));
        $this->hasColumn('typ', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'decimal',
              1 => 'date',
              2 => 'bool',
              3 => 'string',
             ),
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Cecha', array(
             'local' => 'id',
             'foreign' => 'typ_cechy_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'nazwa',
             ),
             'length' => 30,
             ));
        $this->actAs($sluggable0);
    }
}