<?php

/**
 * BadanieTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BadanieTable extends Doctrine_Table
{

  /**
   * Returns an instance of this class.
   *
   * @return BadanieTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Badanie');
  }

  /**
   *
   * @param Pacjent $pacjent
   * @return Doctrine_Collection
   */
  public function myGetBadaniaSorted(Pacjent $pacjent)
  {
    $q = $this
      ->createQuery('b')
      ->addWhere('b.pacjent_id = ?', $pacjent->getId())
      ->orderBy('b.data_badania DESC')
    ;
    
    return $q->execute();
  }

  /**
   *
   * @param Pacjent $pacjent
   * @return Doctrine_Query
   */
  public function myGetBadaniaSortedQuery(Pacjent $pacjent)
  {
    $q = $this
      ->createQuery('b')
      ->select('b.id, b.data_badania, wb.ocena_stanu_guza as ocena')
      ->leftJoin('b.WynikBadania wb')
      ->addWhere('b.pacjent_id = ?', $pacjent->getId())
      ->orderBy('b.data_badania DESC')
    ;

    return $q;
  }

}