<?php

/**
 * Cecha
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    onko_gliwice
 * @subpackage model
 * @author     Paweł Dawczak pawel.dawczak@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Cecha extends BaseCecha
{

  public function save(Doctrine_Connection $conn = null)
  {
    if (!$this->wartosc)
    {
      $this->wartosc = 0;
    }
    parent::save($conn);
  }

}
