<?php

/**
 * CechaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CechaTable extends Doctrine_Table
{

  /**
   * Returns an instance of this class.
   *
   * @return CechaTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Cecha');
  }

}