<?php

/**
 * DietaProduktTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DietaProduktTable extends Doctrine_Table
{

  /**
   * Returns an instance of this class.
   *
   * @return DietaProduktTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('DietaProdukt');
  }

}
