<?php

/**
 * DietaProduktTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DietaProduktTable extends Doctrine_Table
{

  /**
   * Returns an instance of this class.
   *
   * @return DietaProduktTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('DietaProdukt');
  }

  public function myGetProdyktyForDieta(Dieta $dieta)
  {
    $q = $this
      ->createQuery()
      ->addWhere('dieta_id = ?', $dieta->getId())
    ;

    return $q->execute();
  }
}
