<?php

/**
 * DietaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DietaTable extends Doctrine_Table
{

  /**
   * Returns an instance of this class.
   *
   * @return DietaTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Dieta');
  }

}
