<?php

/**
 * Lek
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    onko_gliwice
 * @subpackage model
 * @author     Paweł Dawczak pawel.dawczak@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Lek extends BaseLek
{
  public function __toString()
  {
    return $this->getNazwaLeku();
  }
}
