<?php

/**
 * LekTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LekTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LekTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Lek');
    }
}