<?php

/**
 * PacjentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PacjentTable extends Doctrine_Table
{

  /**
   * Returns an instance of this class.
   *
   * @return PacjentTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Pacjent');
  }

  public function myFindAllQuery($order_column = 'nazwisko', $order_type = 'ASC')
  {
    $q = $this
      ->createQuery('p')
      ->select('p.id, p.imie, p.nazwisko, p.pesel')
      ->orderBy('p.'.$order_column.' '.$order_type)
    ;

    return $q;
  }

  public static function searchQueryHelper($query)
  {
    if (is_numeric($query))
    {
      return self::getInstance()->findLikePeselQuery($query);
    }
    else
    {
      $tmp = explode(',', $query);
      if (count($tmp) == 1)
      {
        return self::getInstance()->findLikeNazwiskoQuery($query);
      }
      else
      {
        return self::getInstance()->findLikeNazwiskoAndImieQuery($tmp[0], trim($tmp[1]));
      }
    }
  }

  public function findLikeQuery(Doctrine_Query $q)
  {
    $q
      ->select('p.id, p.pesel, CONCAT(p.nazwisko, ", ", p.imie) as nazwisko_imie, (YEAR(NOW()) - YEAR(p.data_urodzenia)) as lata')
      ->orderBy('p.nazwisko ASC')
    ;

    return $q;
  }

  public function findLikePeselQuery($pesel)
  {
    $q = $this
      ->createQuery('p')
      ->addWhere('p.pesel LIKE ?', $pesel.'%')
    ;

    return $this->findLikeQuery($q);
  }

  public function findLikeNazwiskoQuery($nazwisko)
  {
    $q = $this
      ->createQuery('p')
      ->addWhere('p.nazwisko LIKE ?', $nazwisko.'%')
    ;

    return $this->findLikeQuery($q);
  }

  public function findLikeNazwiskoAndImieQuery($nazwisko, $imie)
  {
    $q = $this
      ->createQuery('p')
      ->andWhere('p.nazwisko LIKE ?', $nazwisko.'%')
      ->andWhere('p.imie LIKE ?', $imie.'%')
    ;

    return $this->findLikeQuery($q);
  }
}