<?php

/**
 * RadioterapiaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RadioterapiaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RadioterapiaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Radioterapia');
    }
}