<?php

/**
 * RodzajRadioterapiiTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RodzajRadioterapiiTable extends Doctrine_Table
{

  /**
   * Returns an instance of this class.
   *
   * @return RodzajRadioterapiiTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('RodzajRadioterapii');
  }

}
