<?php

/**
 * RodzajRadioterapiiTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RodzajRadioterapiiTable extends Doctrine_Table
{

  /**
   * Returns an instance of this class.
   *
   * @return RodzajRadioterapiiTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('RodzajRadioterapii');
  }

  /**
   * @return Doctrine_Query
   */
  public function myGetSortedRodzajeRadioterapii()
  {
    $q = $this
      ->createQuery('r')
      ->orderBy('r.nazwa')
    ;

    return $q;
  }
}
