<?php

/**
 * TypCechyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TypCechyTable extends Doctrine_Table
{

  /**
   * Returns an instance of this class.
   *
   * @return TypCechyTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('TypCechy');
  }

  /**
   * @param array $slugs
   * @return Doctrine_Collection
   */
  public function myFindBySlugs(array $slugs)
  {
    $q = $this
      ->createQuery('tc')
      ->whereIn('tc.slug', $slugs)
    ;

    return $q->execute();
  }

}