<?php

/**
 * WidmoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WidmoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WidmoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Widmo');
    }
}