<?php

/**
 * WynikBadaniaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WynikBadaniaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WynikBadaniaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WynikBadania');
    }
}