<?php

/**
 * WynikBadania
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    onko_gliwice
 * @subpackage model
 * @author     Paweł Dawczak pawel.dawczak@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class WynikBadania extends BaseWynikBadania
{
  protected static $oceny = array(
    'wz'  => 'Wznowa',
    'stg' => 'Stagnacja',
    'pr'  => 'Progresja',
    'bcg' => 'Brak cech guza'
  );

  public function getOcenaStanuGuzaWord()
  {
    return self::$oceny[$this->getOcenaStanuGuza()];
  }

  /**
   * @param string $type
   * @return Widmo
   */
  public function getWidmo($type = self::WZGORZE)
  {
    foreach ($this->getWidma() as $widmo)
    {
      if ($type == $widmo->getLokalizacja())
      {
        return $widmo;
      }
    }
  }
}
