<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addtypcechy extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('typ_cechy', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'nazwa' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'unique' => true,
              'length' => 30,
             ),
             'typ' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'decimal',
              1 => 'date',
              2 => 'bool',
              3 => 'string',
              ),
              'notnull' => true,
              'length' => NULL,
             ),
             'slug' => 
             array(
              'type' => 'string',
              'length' => 30,
             ),
             ), array(
             'indexes' => 
             array(
              'typ_cechy_sluggable' => 
              array(
              'fields' => 
              array(
               0 => 'slug',
              ),
              'type' => 'unique',
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_polish_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('typ_cechy');
    }
}