<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Adduzywka extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('uzywka', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'badanie_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'typ' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'ap',
              1 => 'bp',
              2 => 'np',
              3 => 'aa',
              4 => 'iu',
              ),
              'length' => NULL,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_polish_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('uzywka');
    }
}