<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addwynikbadania extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('wynik_badania', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'ocena_stanu_guza' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'wz',
              1 => 'pr',
              2 => 'stg',
              3 => 'bcg',
              ),
              'length' => NULL,
             ),
             'badanie_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_polish_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('wynik_badania');
    }
}