<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addbadanie extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('badanie', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'pacjent_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'data_badania' => 
             array(
              'type' => 'date',
              'notnull' => true,
              'length' => 25,
             ),
             'inne' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'menstruacja' => 
             array(
              'type' => 'boolean',
              'default' => 0,
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_polish_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('badanie');
    }
}