<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addwidmo extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('widmo', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'skala_ppm' => 
             array(
              'type' => 'clob',
              'length' => NULL,
             ),
             'widmo' => 
             array(
              'type' => 'clob',
              'length' => NULL,
             ),
             'linia_bazowa' => 
             array(
              'type' => 'clob',
              'length' => NULL,
             ),
             'widmo_bazowa' => 
             array(
              'type' => 'clob',
              'length' => NULL,
             ),
             'lokalizacja' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'wz',
              1 => 'isc',
              2 => 'isp',
              ),
              'length' => NULL,
             ),
             'rozmiar_voxela_x' => 
             array(
              'type' => 'decimal',
              'scale' => 2,
              'notnull' => true,
              'length' => 5,
             ),
             'rozmiar_voxela_y' => 
             array(
              'type' => 'decimal',
              'scale' => 2,
              'notnull' => true,
              'length' => 5,
             ),
             'rozmiar_voxela_z' => 
             array(
              'type' => 'decimal',
              'scale' => 2,
              'notnull' => true,
              'length' => 5,
             ),
             'stezenia' => 
             array(
              'type' => 'clob',
              'length' => NULL,
             ),
             'te' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'tr' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'ns' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'wynik_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_polish_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('widmo');
    }
}