<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addpacjent extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('pacjent', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'imie' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 20,
             ),
             'nazwisko' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 50,
             ),
             'pesel' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'unique' => true,
              'length' => 11,
             ),
             'data_urodzenia' => 
             array(
              'type' => 'date',
              'notnull' => true,
              'length' => 25,
             ),
             'plec' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'm',
              1 => 'k',
              ),
              'length' => NULL,
             ),
             'wzrost' => 
             array(
              'type' => 'smallint',
              'notnull' => true,
              'length' => NULL,
             ),
             'waga' => 
             array(
              'type' => 'decimal',
              'scale' => 2,
              'notnull' => true,
              'length' => 5,
             ),
             'reka' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'p',
              1 => 'l',
              2 => 'o',
              ),
              'length' => NULL,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_polish_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('pacjent');
    }
}