<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addcecha extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('cecha', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'uzywka_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'typ_cechy_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'wartosc' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_polish_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('cecha');
    }
}