<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version23 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('dieta', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'badanie_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'bezmiesna' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             'zroznicowana' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_polish_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('dieta_produkt', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'dieta_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'produkt_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'duza_ilosc' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_polish_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('produkt', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'nazwa' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_polish_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('dieta');
        $this->dropTable('dieta_produkt');
        $this->dropTable('produkt');
    }
}