<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version22 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('chemioterapia', 'chemioterapia_pacjent_id_pacjent_id', array(
             'name' => 'chemioterapia_pacjent_id_pacjent_id',
             'local' => 'pacjent_id',
             'foreign' => 'id',
             'foreignTable' => 'pacjent',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('chemioterapia', 'chemioterapia_pacjent_id', array(
             'fields' => 
             array(
              0 => 'pacjent_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('chemioterapia', 'chemioterapia_pacjent_id_pacjent_id');
        $this->removeIndex('chemioterapia', 'chemioterapia_pacjent_id', array(
             'fields' => 
             array(
              0 => 'pacjent_id',
             ),
             ));
    }
}