<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version21 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('chemioterapia', 'pacjent_id', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('chemioterapia', 'pacjent_id');
    }
}