<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version19 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('chemioterapia', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'data_rozpoczecia' => 
             array(
              'type' => 'date',
              'length' => '25',
             ),
             'data_zakonczenia' => 
             array(
              'type' => 'date',
              'length' => '25',
             ),
             'lek_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_polish_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('lek', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'nazwa_leku' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'rodzaj' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'a',
              1 => 'c',
              2 => 'i',
              ),
              'length' => '',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_polish_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('chemioterapia');
        $this->dropTable('lek');
    }
}