<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version25 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('dieta', 'najczesciej_spozywane_produkty', 'clob', '', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('dieta', 'najczesciej_spozywane_produkty');
    }
}