<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version30 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('wynik_badania', 'sdat', 'blob', '', array(
             ));
        $this->addColumn('wynik_badania', 'spar', 'clob', '', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('wynik_badania', 'sdat');
        $this->removeColumn('wynik_badania', 'spar');
    }
}
