<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version31 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('widmo', 'skala_ppm');
        $this->removeColumn('widmo', 'widmo');
        $this->removeColumn('widmo', 'linia_bazowa');
        $this->removeColumn('widmo', 'widmo_bazowa');
        $this->removeColumn('widmo', 'stezenia');
        $this->removeColumn('wynik_badania', 'sdat');
        $this->removeColumn('wynik_badania', 'spar');
        $this->addColumn('widmo', 'sdat', 'blob', '', array(
             ));
        $this->addColumn('widmo', 'spar', 'clob', '', array(
             ));
    }

    public function down()
    {
        $this->addColumn('widmo', 'skala_ppm', 'clob', '', array(
             ));
        $this->addColumn('widmo', 'widmo', 'clob', '', array(
             ));
        $this->addColumn('widmo', 'linia_bazowa', 'clob', '', array(
             ));
        $this->addColumn('widmo', 'widmo_bazowa', 'clob', '', array(
             ));
        $this->addColumn('wynik_badania', 'sdat', 'blob', '', array(
             ));
        $this->addColumn('wynik_badania', 'spar', 'clob', '', array(
             ));
        $this->removeColumn('widmo', 'sdat');
        $this->removeColumn('widmo', 'spar');
    }
}
