<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version29 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('widmo', 'widmo_lokalizacja_id_lokalizacja_id', array(
             'name' => 'widmo_lokalizacja_id_lokalizacja_id',
             'local' => 'lokalizacja_id',
             'foreign' => 'id',
             'foreignTable' => 'lokalizacja',
             ));
        $this->addIndex('widmo', 'widmo_lokalizacja_id', array(
             'fields' => 
             array(
              0 => 'lokalizacja_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('widmo', 'widmo_lokalizacja_id_lokalizacja_id');
        $this->removeIndex('widmo', 'widmo_lokalizacja_id', array(
             'fields' => 
             array(
              0 => 'lokalizacja_id',
             ),
             ));
    }
}