<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version26 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('rodzaj_radioterapii', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'skrot' => 
             array(
              'type' => 'string',
              'length' => '5',
             ),
             'nazwa' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_polish_ci',
             'charset' => 'utf8',
             ));
        $this->addColumn('radioterapia', 'rodzaj_radioterapii_id', 'int', '8', array(
             ));
    }

    public function down()
    {
        $this->dropTable('rodzaj_radioterapii');
        $this->removeColumn('radioterapia', 'rodzaj_radioterapii_id');
    }
}